"btcd" :  [
        {
                "url" : "localhost:8332",
                "auth" : "username",
                "pass" : "password",
                "notify" : true
        }
],
"btcaddress" : "bc1qlgx8...zqhncexu0",
"logdir" : "logs"
}
